data_type: shard
dataloader_args:
  batch_size: 128
  drop_last: true
  num_workers: 16
  pin_memory: Ture
  prefetch_factor: 8
dataset_args:
  aug_prob: 0.2
  fbank_args:
    dither: 0.0
    frame_length: 25
    frame_shift: 10
    num_mel_bins: 80
  num_frms: 300
  resample_rate: 16000
  shuffle: true
  shuffle_args:
    shuffle_size: 2500
  spec_aug: false
  spec_aug_args:
    max_f: 8
    max_t: 10
    num_f_mask: 1
    num_t_mask: 1
    prob: 0.6
  speed_perturb: true
enable_amp: false
exp_dir: exp/CAMPPlus-epoch60-depthResblock32_64-num_frame300
gpus:
- 0
- 1
log_batch_interval: 100
loss: CrossEntropyLoss
loss_args: {}
margin_scheduler: MarginScheduler
margin_update:
  epoch_iter: 4265
  final_margin: 0.2
  fix_start_epoch: 25
  increase_start_epoch: 15
  increase_type: exp
  initial_margin: 0.0
  update_margin: true
model: CAMPPlus
model_args:
  embed_dim: 512
  feat_dim: 80
  pooling_func: TSTP
model_init: null
noise_data: data/musan/lmdb
num_avg: 1
num_epochs: 60
optimizer: SGD
optimizer_args:
  lr: 0.1
  momentum: 0.9
  nesterov: true
  weight_decay: 0.0001
projection_args:
  do_lm: false
  easy_margin: false
  embed_dim: 512
  num_class: 17982
  project_type: arc_margin
  scale: 32.0
reverb_data: data/rirs/lmdb
save_epoch_interval: 2
scheduler: ExponentialDecrease
scheduler_args:
  epoch_iter: 4265
  final_lr: 0.0001
  initial_lr: 0.1
  num_epochs: 60
  scale_ratio: 2.0
  warm_from_zero: true
  warm_up_epoch: 5
seed: 42
train_data: data/vox2_dev/shard.list
train_label: data/vox2_dev/utt2spk
